//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourieCSharp.Mesure {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service/", ConfigurationName="Mesure.Data_Service")]
    public interface Data_Service {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/ajouterDataRequest", ReplyAction="http://Service/Data_Service/ajouterDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Mesure.ajouterDataResponse ajouterData(SourieCSharp.Mesure.ajouterDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/ajouterDataRequest", ReplyAction="http://Service/Data_Service/ajouterDataResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.ajouterDataResponse> ajouterDataAsync(SourieCSharp.Mesure.ajouterDataRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/supprimerDataRequest", ReplyAction="http://Service/Data_Service/supprimerDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Mesure.supprimerDataResponse supprimerData(SourieCSharp.Mesure.supprimerDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/supprimerDataRequest", ReplyAction="http://Service/Data_Service/supprimerDataResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.supprimerDataResponse> supprimerDataAsync(SourieCSharp.Mesure.supprimerDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/getListDataRequest", ReplyAction="http://Service/Data_Service/getListDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SourieCSharp.Mesure.getListDataResponse getListData(SourieCSharp.Mesure.getListDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/getListDataRequest", ReplyAction="http://Service/Data_Service/getListDataResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.getListDataResponse> getListDataAsync(SourieCSharp.Mesure.getListDataRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/modifierDataRequest", ReplyAction="http://Service/Data_Service/modifierDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Mesure.modifierDataResponse modifierData(SourieCSharp.Mesure.modifierDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/modifierDataRequest", ReplyAction="http://Service/Data_Service/modifierDataResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.modifierDataResponse> modifierDataAsync(SourieCSharp.Mesure.modifierDataRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/FindBydataRequest", ReplyAction="http://Service/Data_Service/FindBydataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SourieCSharp.Mesure.FindBydataResponse FindBydata(SourieCSharp.Mesure.FindBydataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Data_Service/FindBydataRequest", ReplyAction="http://Service/Data_Service/FindBydataResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.FindBydataResponse> FindBydataAsync(SourieCSharp.Mesure.FindBydataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service/")]
    public partial class data : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private int id_dataField;
        
        private int id_typedataField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_data {
            get {
                return this.id_dataField;
            }
            set {
                this.id_dataField = value;
                this.RaisePropertyChanged("id_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_typedata {
            get {
                return this.id_typedataField;
            }
            set {
                this.id_typedataField = value;
                this.RaisePropertyChanged("id_typedata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterData", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class ajouterDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data arg0;
        
        public ajouterDataRequest() {
        }
        
        public ajouterDataRequest(SourieCSharp.Mesure.data arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterDataResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class ajouterDataResponse {
        
        public ajouterDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerData", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class supprimerDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data arg0;
        
        public supprimerDataRequest() {
        }
        
        public supprimerDataRequest(SourieCSharp.Mesure.data arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerDataResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class supprimerDataResponse {
        
        public supprimerDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListData", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getListDataRequest {
        
        public getListDataRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListDataResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getListDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data[] @return;
        
        public getListDataResponse() {
        }
        
        public getListDataResponse(SourieCSharp.Mesure.data[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierData", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class modifierDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data arg0;
        
        public modifierDataRequest() {
        }
        
        public modifierDataRequest(SourieCSharp.Mesure.data arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierDataResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class modifierDataResponse {
        
        public modifierDataResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindBydata", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class FindBydataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data arg0;
        
        public FindBydataRequest() {
        }
        
        public FindBydataRequest(SourieCSharp.Mesure.data arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindBydataResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class FindBydataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Mesure.data[] @return;
        
        public FindBydataResponse() {
        }
        
        public FindBydataResponse(SourieCSharp.Mesure.data[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Data_ServiceChannel : SourieCSharp.Mesure.Data_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Data_ServiceClient : System.ServiceModel.ClientBase<SourieCSharp.Mesure.Data_Service>, SourieCSharp.Mesure.Data_Service {
        
        public Data_ServiceClient() {
        }
        
        public Data_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Data_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Data_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Data_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Mesure.ajouterDataResponse SourieCSharp.Mesure.Data_Service.ajouterData(SourieCSharp.Mesure.ajouterDataRequest request) {
            return base.Channel.ajouterData(request);
        }
        
        public void ajouterData(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.ajouterDataRequest inValue = new SourieCSharp.Mesure.ajouterDataRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Mesure.ajouterDataResponse retVal = ((SourieCSharp.Mesure.Data_Service)(this)).ajouterData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.ajouterDataResponse> SourieCSharp.Mesure.Data_Service.ajouterDataAsync(SourieCSharp.Mesure.ajouterDataRequest request) {
            return base.Channel.ajouterDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Mesure.ajouterDataResponse> ajouterDataAsync(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.ajouterDataRequest inValue = new SourieCSharp.Mesure.ajouterDataRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Mesure.Data_Service)(this)).ajouterDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Mesure.supprimerDataResponse SourieCSharp.Mesure.Data_Service.supprimerData(SourieCSharp.Mesure.supprimerDataRequest request) {
            return base.Channel.supprimerData(request);
        }
        
        public void supprimerData(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.supprimerDataRequest inValue = new SourieCSharp.Mesure.supprimerDataRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Mesure.supprimerDataResponse retVal = ((SourieCSharp.Mesure.Data_Service)(this)).supprimerData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.supprimerDataResponse> SourieCSharp.Mesure.Data_Service.supprimerDataAsync(SourieCSharp.Mesure.supprimerDataRequest request) {
            return base.Channel.supprimerDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Mesure.supprimerDataResponse> supprimerDataAsync(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.supprimerDataRequest inValue = new SourieCSharp.Mesure.supprimerDataRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Mesure.Data_Service)(this)).supprimerDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Mesure.getListDataResponse SourieCSharp.Mesure.Data_Service.getListData(SourieCSharp.Mesure.getListDataRequest request) {
            return base.Channel.getListData(request);
        }
        
        public SourieCSharp.Mesure.data[] getListData() {
            SourieCSharp.Mesure.getListDataRequest inValue = new SourieCSharp.Mesure.getListDataRequest();
            SourieCSharp.Mesure.getListDataResponse retVal = ((SourieCSharp.Mesure.Data_Service)(this)).getListData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.getListDataResponse> SourieCSharp.Mesure.Data_Service.getListDataAsync(SourieCSharp.Mesure.getListDataRequest request) {
            return base.Channel.getListDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Mesure.getListDataResponse> getListDataAsync() {
            SourieCSharp.Mesure.getListDataRequest inValue = new SourieCSharp.Mesure.getListDataRequest();
            return ((SourieCSharp.Mesure.Data_Service)(this)).getListDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Mesure.modifierDataResponse SourieCSharp.Mesure.Data_Service.modifierData(SourieCSharp.Mesure.modifierDataRequest request) {
            return base.Channel.modifierData(request);
        }
        
        public void modifierData(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.modifierDataRequest inValue = new SourieCSharp.Mesure.modifierDataRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Mesure.modifierDataResponse retVal = ((SourieCSharp.Mesure.Data_Service)(this)).modifierData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.modifierDataResponse> SourieCSharp.Mesure.Data_Service.modifierDataAsync(SourieCSharp.Mesure.modifierDataRequest request) {
            return base.Channel.modifierDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Mesure.modifierDataResponse> modifierDataAsync(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.modifierDataRequest inValue = new SourieCSharp.Mesure.modifierDataRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Mesure.Data_Service)(this)).modifierDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Mesure.FindBydataResponse SourieCSharp.Mesure.Data_Service.FindBydata(SourieCSharp.Mesure.FindBydataRequest request) {
            return base.Channel.FindBydata(request);
        }
        
        public SourieCSharp.Mesure.data[] FindBydata(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.FindBydataRequest inValue = new SourieCSharp.Mesure.FindBydataRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Mesure.FindBydataResponse retVal = ((SourieCSharp.Mesure.Data_Service)(this)).FindBydata(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Mesure.FindBydataResponse> SourieCSharp.Mesure.Data_Service.FindBydataAsync(SourieCSharp.Mesure.FindBydataRequest request) {
            return base.Channel.FindBydataAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Mesure.FindBydataResponse> FindBydataAsync(SourieCSharp.Mesure.data arg0) {
            SourieCSharp.Mesure.FindBydataRequest inValue = new SourieCSharp.Mesure.FindBydataRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Mesure.Data_Service)(this)).FindBydataAsync(inValue);
        }
    }
}
