//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourieCSharp.Log {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Service/", ConfigurationName="Log.Log_Service")]
    public interface Log_Service {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/supprimerLogRequest", ReplyAction="http://Service/Log_Service/supprimerLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Log.supprimerLogResponse supprimerLog(SourieCSharp.Log.supprimerLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/supprimerLogRequest", ReplyAction="http://Service/Log_Service/supprimerLogResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Log.supprimerLogResponse> supprimerLogAsync(SourieCSharp.Log.supprimerLogRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/ajouterLogRequest", ReplyAction="http://Service/Log_Service/ajouterLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Log.ajouterLogResponse ajouterLog(SourieCSharp.Log.ajouterLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/ajouterLogRequest", ReplyAction="http://Service/Log_Service/ajouterLogResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Log.ajouterLogResponse> ajouterLogAsync(SourieCSharp.Log.ajouterLogRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/modifierLogRequest", ReplyAction="http://Service/Log_Service/modifierLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SourieCSharp.Log.modifierLogResponse modifierLog(SourieCSharp.Log.modifierLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/modifierLogRequest", ReplyAction="http://Service/Log_Service/modifierLogResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Log.modifierLogResponse> modifierLogAsync(SourieCSharp.Log.modifierLogRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/getListLogRequest", ReplyAction="http://Service/Log_Service/getListLogResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SourieCSharp.Log.getListLogResponse getListLog(SourieCSharp.Log.getListLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Service/Log_Service/getListLogRequest", ReplyAction="http://Service/Log_Service/getListLogResponse")]
        System.Threading.Tasks.Task<SourieCSharp.Log.getListLogResponse> getListLogAsync(SourieCSharp.Log.getListLogRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Service/")]
    public partial class log : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dateField;
        
        private int id_logField;
        
        private string msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id_log {
            get {
                return this.id_logField;
            }
            set {
                this.id_logField = value;
                this.RaisePropertyChanged("id_log");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
                this.RaisePropertyChanged("msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerLog", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class supprimerLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Log.log arg0;
        
        public supprimerLogRequest() {
        }
        
        public supprimerLogRequest(SourieCSharp.Log.log arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="supprimerLogResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class supprimerLogResponse {
        
        public supprimerLogResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterLog", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class ajouterLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Log.log arg0;
        
        public ajouterLogRequest() {
        }
        
        public ajouterLogRequest(SourieCSharp.Log.log arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ajouterLogResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class ajouterLogResponse {
        
        public ajouterLogResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierLog", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class modifierLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Log.log arg0;
        
        public modifierLogRequest() {
        }
        
        public modifierLogRequest(SourieCSharp.Log.log arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifierLogResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class modifierLogResponse {
        
        public modifierLogResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListLog", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getListLogRequest {
        
        public getListLogRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getListLogResponse", WrapperNamespace="http://Service/", IsWrapped=true)]
    public partial class getListLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Service/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SourieCSharp.Log.log[] @return;
        
        public getListLogResponse() {
        }
        
        public getListLogResponse(SourieCSharp.Log.log[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Log_ServiceChannel : SourieCSharp.Log.Log_Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Log_ServiceClient : System.ServiceModel.ClientBase<SourieCSharp.Log.Log_Service>, SourieCSharp.Log.Log_Service {
        
        public Log_ServiceClient() {
        }
        
        public Log_ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Log_ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Log_ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Log_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Log.supprimerLogResponse SourieCSharp.Log.Log_Service.supprimerLog(SourieCSharp.Log.supprimerLogRequest request) {
            return base.Channel.supprimerLog(request);
        }
        
        public void supprimerLog(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.supprimerLogRequest inValue = new SourieCSharp.Log.supprimerLogRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Log.supprimerLogResponse retVal = ((SourieCSharp.Log.Log_Service)(this)).supprimerLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Log.supprimerLogResponse> SourieCSharp.Log.Log_Service.supprimerLogAsync(SourieCSharp.Log.supprimerLogRequest request) {
            return base.Channel.supprimerLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Log.supprimerLogResponse> supprimerLogAsync(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.supprimerLogRequest inValue = new SourieCSharp.Log.supprimerLogRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Log.Log_Service)(this)).supprimerLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Log.ajouterLogResponse SourieCSharp.Log.Log_Service.ajouterLog(SourieCSharp.Log.ajouterLogRequest request) {
            return base.Channel.ajouterLog(request);
        }
        
        public void ajouterLog(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.ajouterLogRequest inValue = new SourieCSharp.Log.ajouterLogRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Log.ajouterLogResponse retVal = ((SourieCSharp.Log.Log_Service)(this)).ajouterLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Log.ajouterLogResponse> SourieCSharp.Log.Log_Service.ajouterLogAsync(SourieCSharp.Log.ajouterLogRequest request) {
            return base.Channel.ajouterLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Log.ajouterLogResponse> ajouterLogAsync(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.ajouterLogRequest inValue = new SourieCSharp.Log.ajouterLogRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Log.Log_Service)(this)).ajouterLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Log.modifierLogResponse SourieCSharp.Log.Log_Service.modifierLog(SourieCSharp.Log.modifierLogRequest request) {
            return base.Channel.modifierLog(request);
        }
        
        public void modifierLog(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.modifierLogRequest inValue = new SourieCSharp.Log.modifierLogRequest();
            inValue.arg0 = arg0;
            SourieCSharp.Log.modifierLogResponse retVal = ((SourieCSharp.Log.Log_Service)(this)).modifierLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Log.modifierLogResponse> SourieCSharp.Log.Log_Service.modifierLogAsync(SourieCSharp.Log.modifierLogRequest request) {
            return base.Channel.modifierLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Log.modifierLogResponse> modifierLogAsync(SourieCSharp.Log.log arg0) {
            SourieCSharp.Log.modifierLogRequest inValue = new SourieCSharp.Log.modifierLogRequest();
            inValue.arg0 = arg0;
            return ((SourieCSharp.Log.Log_Service)(this)).modifierLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SourieCSharp.Log.getListLogResponse SourieCSharp.Log.Log_Service.getListLog(SourieCSharp.Log.getListLogRequest request) {
            return base.Channel.getListLog(request);
        }
        
        public SourieCSharp.Log.log[] getListLog() {
            SourieCSharp.Log.getListLogRequest inValue = new SourieCSharp.Log.getListLogRequest();
            SourieCSharp.Log.getListLogResponse retVal = ((SourieCSharp.Log.Log_Service)(this)).getListLog(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SourieCSharp.Log.getListLogResponse> SourieCSharp.Log.Log_Service.getListLogAsync(SourieCSharp.Log.getListLogRequest request) {
            return base.Channel.getListLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<SourieCSharp.Log.getListLogResponse> getListLogAsync() {
            SourieCSharp.Log.getListLogRequest inValue = new SourieCSharp.Log.getListLogRequest();
            return ((SourieCSharp.Log.Log_Service)(this)).getListLogAsync(inValue);
        }
    }
}
